### ISSUE TITLE
not clear how to contribute to the wiki

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/TAO-Wiki#1]
would it be possible to add a description on how to add to the wiki?
the wiki doesn't tell you how to contribute.

- when forking this repo the wiki doesn't get forked.
- when cloning the wiki, the following error occurs:
```
Resolving deltas: 100% (92/92)
Resolving deltas: 100% (92/92), done.
error: invalid path 'Console:-Threaded-"WIP"-animation.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by VictorStepanov** [comment]
Have you tried  https://github.com/techartorg/techartorg.github.io

https://techartorg.github.io/

**Comment by VictorStepanov** [comment]
Also I think the instruction are here 
https://github.com/techartorg/TAO-Wiki/wiki

**Comment by hannesdelbeke** [comment]
We're talking about 2 different wikis / repos.

## techartorg.github.io
You linked me too https://github.com/techartorg/techartorg.github.io which hosts the https://tech-artists.org/ wiki
But that is a different repo than this one!

## TAO-Wiki

My question is regarding https://github.com/techartorg/TAO-Wiki

> Also I think the instruction are here https://github.com/techartorg/TAO-Wiki/wiki

This issue was created after trying to follow those instructions.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3758308/191853706-c2441e77-2c1e-44a5-b412-da755d44b5fd.png">

## Question
So is this repo not used anymore, and everything is now happening in https://github.com/techartorg/techartorg.github.io ?

**Comment by hannesdelbeke** [comment]
The instructions assume you have admin access.
after creating a github repo, the add button appears on my repo.
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3758308/191857264-cc52d612-a346-4850-9a69-a264725c0f4f.png">

So it's fair to say this wiki can't be edited by the community currently.

**Comment by TravisEvashkevich** [comment]
It can be edited by the community but you have to be added to the community members group. 
You can ask to be added on Slack.

I believe the idea right now is that people should be using the github.io one rather than the actual wiki here so it can be trawled easier by search engines (as at least when it was made, search engines don't/can't see the wiki?)

I do think that the github.io one probably needs an overhaul as I've never been able to get it to work (or maybe exactly once)

I think @instinct-vfx had a version that looked promising a while back but I don't know if we've ever got it looked at much more than a prototype.

**Comment by TravisEvashkevich** [comment]
The .io is the "new" wiki that is supposed to be used and contributed to as
it can be indexed apparently while the other can not without being added to
the TAO org (which can be asked on the slack easily enough)

The new one does need a better doc as I can't get it to work myself either,
or a better alternative setup.

**Comment by hannesdelbeke** [comment]
Thanks for clarifying Travis
